counting_process: counting_process.c counting_process_sem.c counting_process_flock.c
	gcc -o counting_process counting_process.c
	gcc -o counting_process_sem counting_process_sem.c
	gcc -o counting_process_flock counting_process_flock.c