.\" Manpage for simple_prog
.\" Contact benedict.schwind@stud.fh-rosenheim.de to correct errors or
.TH man 7 "14 Septenber 2018" "1.0" "simple_prog man page"
.SH NAME
simple_prog \- do something useful
.SH SYNOPSIS
simple_prog
.SH DESCRIPTION
simple_prog is a program that does something useful.
.SH OPTIONS
The simple_prog does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Benedict Schwind (benedict.schwind@stud.fh-rosenheim.de)